name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: prod_docker
    steps:
      - name: Pull latest code
        working-directory: /srv/uvacns-website
        run: git pull

      - name: Rebuild and restart
        working-directory: /srv/uvacns-website
        run: docker compose up -d --build
